<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Istok.WebGPU.View</RootNamespace>
        <IsPackable>true</IsPackable>
        <PackageId>Istok.WebGPU.View</PackageId>
        <Description>Cross-platform view abstractions (windowing/surface) for Istok.WebGPU.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Silk.NET.Maths" Version="2.22.0" />
    </ItemGroup>

</Project>
