<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>preview</LangVersion>
        <RootNamespace>Istok.WebGPU</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Istok.WebGPU.LowLevel\Istok.WebGPU.LowLevel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Silk.NET.Core" Version="2.23.0" />
    </ItemGroup>
    
</Project>
