<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-ios</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>Istok.WebGPU.LowLevel</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Silk.NET.Core" Version="2.23.0" />
    </ItemGroup>

</Project>
