<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-android</TargetFramework>
        <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <!--
          Enable trim analyzers for Android class libraries.
          To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
        -->
        <IsTrimmable>true</IsTrimmable>
        <RootNamespace>Istok.WebGPU.Native.Android</RootNamespace>
        <IsPackable>true</IsPackable>
        <PackageId>Istok.WebGPU.Native.Android</PackageId>
        <Description>Native WebGPU runtime binaries (wgpu-native) for Android, packaged for use with Istok.WebGPU.</Description>
    </PropertyGroup>

    <ItemGroup>
        <None Include="runtimes\**\*" Exclude="**\.DS_Store" Pack="true" PackagePath="runtimes/" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>